http:
  routers:
    professorit-public-api:
      rule: "Host(`professorit.ru`) && PathPrefix(`/api/public/`)"
      priority: 100
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: professorit-public-api
    professorit-public-api-www:
      rule: "Host(`www.professorit.ru`) && PathPrefix(`/api/public/`)"
      priority: 100
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: professorit-public-api
    professorit-site:
      rule: "Host(`professorit.ru`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: professorit-site
    professorit-site-www:
      rule: "Host(`www.professorit.ru`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: professorit-site

  services:
    professorit-public-api:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8084"
    professorit-site:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8083"
